# Generated by Django 4.2.7 on 2026-07-17 17:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("icono", models.CharField(default="🍳", max_length=50)),
            ],
            options={
                "verbose_name_plural": "Categorías",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Receta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "ingredientes",
                    models.TextField(
                        help_text="Escribe cada ingrediente en una línea separada"
                    ),
                ),
                (
                    "instrucciones",
                    models.TextField(
                        help_text="Escribe cada paso en una línea separada"
                    ),
                ),
                ("tiempo_preparacion", models.IntegerField(help_text="En minutos")),
                (
                    "tiempo_coccion",
                    models.IntegerField(default=0, help_text="En minutos"),
                ),
                ("porciones", models.IntegerField(default=4)),
                (
                    "dificultad",
                    models.CharField(
                        choices=[
                            ("Fácil", "Fácil"),
                            ("Medio", "Medio"),
                            ("Difícil", "Difícil"),
                        ],
                        default="Fácil",
                        max_length=10,
                    ),
                ),
                ("imagen", models.ImageField(upload_to="recetas/%Y/%m/%d/")),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("actualizada_en", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recetas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recetas",
                        to="recetas_app.categoria",
                    ),
                ),
            ],
            options={
                "ordering": ["-creada_en"],
            },
        ),
        migrations.CreateModel(
            name="Puntuacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puntuacion",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comentario", models.TextField(blank=True)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("actualizada_en", models.DateTimeField(auto_now=True)),
                (
                    "receta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puntuaciones",
                        to="recetas_app.receta",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puntuaciones_dadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creada_en"],
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "foto_perfil",
                    models.ImageField(
                        blank=True, null=True, upload_to="perfiles/%Y/%m/%d/"
                    ),
                ),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                ("pais", models.CharField(blank=True, max_length=100)),
                (
                    "preferencias_dieteticas",
                    models.TextField(
                        blank=True, help_text="Ej: Vegetariano, Sin gluten, etc."
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="receta",
            index=models.Index(
                fields=["-creada_en"], name="recetas_app_creada__939181_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receta",
            index=models.Index(
                fields=["categoria"], name="recetas_app_categor_4a4ff0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receta",
            index=models.Index(fields=["autor"], name="recetas_app_autor_i_eeef45_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="puntuacion",
            unique_together={("receta", "usuario")},
        ),
    ]
