# Generated by Django 4.2.7 on 2026-08-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetas_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receta",
            name="imagen_alto",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="receta",
            name="imagen_ancho",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="receta",
            name="imagen_numero",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="receta",
            name="imagen_size_kb",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="receta",
            name="imagen",
            field=models.ImageField(upload_to="recetas/images/%Y/%m/%d/"),
        ),
    ]
